---
title: Architecture
---
flowchart TB
  IngestEngine-->Neo4JServer
  ToolingServer-->Neo4JServer
  User-->AGUIClient
  AGUIClient-->OpenAPICypherAgent
  OpenAPICypherAgent-->LLM
  OpenAPICypherAgent-->ToolingServer
